### ISSUE TITLE
Support .net core sdk 2.0

### ISSUE THREAD

**Issue by enricosada** [dotnet/netcorecli-fsc#108]
blocked by #92

**Comment by lambdakris** [comment]
I had started working on the 2.0 version of the F# templates in https://github.com/dotnet/templating and I think this affects them since the templates target netcoreapp2.0.

**Comment by enricosada** [comment]
The only change will be `FSharp.NET.Sdk` version, who will be `2.0.*` (instead of `1.0.*`).
I'll release a temporary `2.0.0` (or `2.0.0-beta`) asap so at least template will restore correctly, and we can fix it later with a new package

**Comment by Alxandr** [comment]
@enricosada any news on this? You said you'd release a temp 2.0.0, was that o n a myget repo?

**Comment by lvicentesanchez** [comment]
Any news on this @enricosada ?

**Comment by lvicentesanchez** [comment]
I tried to bump `FSharp.Net.Sdk` to `2.0.*` in the project, but it doesn't exist.

**Comment by enricosada** [comment]
Closing. Ref https://github.com/dotnet/netcorecli-fsc/wiki/.NET-Core-SDK-2.0.0-preview2#notes 

The `FSharp.NET.Sdk` used in sdk 1.0 was deprecated in favor of including the sdk integration needed for F# inside `Microsoft.NET.Sdk`.

More info in the [F# RFC FS-1032 Support for F# in the dotnet sdk](https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1032-fsharp-in-dotnet-sdk.md)

**For summary of differences and migration from 1.0, see [[How to migrate 1.0 projects to 2.0|How-to-migrate-1.0-projects-to-2.0]]**


Added notes about [not supporting 2.0.0-preview1](https://github.com/dotnet/netcorecli-fsc/wiki/.NET-Core-SDK-2.0.0-preview1)
