### ISSUE TITLE
Error running base MVC

### ISSUE THREAD

**Issue by jowensboggs** [dotnet/netcorecli-fsc#11]
When fleshing out a base Web Kestrel hosted MVC app, the app fails to start with the error:
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes' or one of its dependencies. The system cannot find the file specified.

To Reproduce
1) dotnet new --lang=fsharp
2) add 
'''    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Mvc": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0-rc2-final" 
''' to dependencies in project.json
3) Add the F# code to initialzie Kestrel & MVC (attached)
4) dotnet build (works)
5) dotnet run (fails with Could not load file or assembly 'System, Version=2.0.5.0, ... )

If you remove the "portable-net45+win81" from tools.dotnet-compile-fsc & frameworks elements of the project.json, dotnet run will succeed, but dotnet restore will fail
Attached project.json and Program.fs
[Mvc.zip](https://github.com/dotnet/netcorecli-fsc/files/318662/Mvc.zip)

**Comment by enricosada** [comment]
Closing.

now `dotnet new -l fsharp -t web` create an working aspnet mvc project (preview2, preview2.1, msbuild based > preview4)
