### ISSUE TITLE
F# RFC FS-1032 - Support for F# in the dotnet sdk

### ISSUE THREAD

**Issue by dsyme** [dotnet/netcorecli-fsc#115]
A proposal is being put forward by Microsoft to include F# functionality directly into the dotnet SDK (also known as "Microsoft.NET.Sdk").   Although it is not a language change, this is being handled via the F# RFC mechanism as [F# RFC 1032 - add F# support to the dotnet sdk](https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1032-fsharp-in-dotnet-sdk.md), which is the primary next-generation cross-platform SDK for .NET Framework and .NET Core programming. This work can be seen as the next logical step in the evolution of the FSharp.NET.Sdk which is published from this repo.

This proposal directly impacts the work of this project.  Please discuss the proposal and give feedback on it, either below, or on the RFC thread, or on one of the linked PR discussion threads. This proposal has not yet been fully implemented or committed, so it is very important that we discuss it as soon as possible and get eyes on the implementation. Some of the work has started, so we are playing catch-up with regard to transparency here.

For practical purposes the proposal would change very little about .NET Core programming with F#. At the most, if the work is completed, it will simply allow the removal of the reference to FSharp.NET.Sdk from the first line of project files, and allow the optional removal of a reference to the F# compiler package. Benefits such as an NGEN'd compiler are explained in the RFC, as are some of the drawbacks raised by community members.

**Comment by enricosada** [comment]
Closing.

Applied with `2.0.0-preview2`, see [2.0.0-preview2 wiki page for more info](https://github.com/dotnet/netcorecli-fsc/wiki/.NET-Core-SDK-2.0.0-preview2)
