### ISSUE TITLE
Unable to reproduce test project

### ISSUE THREAD

**Issue by aggieben** [dotnet/netcorecli-fsc#118]
I tried to create a test project like the one in examples/rc4/xunittests, but didn't have much luck.  The biggest difference was that I added Paket to the mix, both in xunittests and in my test project.  However, the xunittests project still worked (i.e., the one trivial test was found and executed), whereas in my test project, no tests were discovered.  I'm a bit at a loss as to how this has happened, and I'm hoping I can help you diagnose it.  See the attached 
[fs-test-repro.zip](https://github.com/dotnet/netcorecli-fsc/files/1049393/fs-test-repro.zip) for my attempt, and the paket-ized version of xunittests 
[xunittests.zip](https://github.com/dotnet/netcorecli-fsc/files/1049394/xunittests.zip).

Included in the fs-test-repro.zip are two sorted copies of the project.assets.json files from the two projects, and when you diff them, you'll see that there are no differences except that some of the packages are referenced by a short version like "4.3" instead of "4.3.0".

Please let me know if there's any other information I can provide.

**Comment by enricosada** [comment]
@aggieben can you try using a `dotnet new xunit -lang f#` template? and try that before adding paket?
if works, should be moved to paket repo

**Comment by aggieben** [comment]
Yeah, the bare project worked.  

```
✔ ~/proj/scratch/newtest 
03:58 $ dotnet --info
.NET Command Line Tools (2.0.0-preview2-005905)

Product Information:
 Version:            2.0.0-preview2-005905
 Commit SHA-1 hash:  2cc5612fec

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0-preview2-005905

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-002093-00
  Build    : 1a195046fd92bd73d993d804bea2f4506c2b56f1

✔ ~/proj/scratch/newtest 
03:58 $ 
```

**Comment by enricosada** [comment]
@aggieben `2.0.0-preview1` doesnt work.
use `1.0.*` or `2.0.0-preview2`, and check default template for xunit (`dotnet new xunit -lang f#`)

If doesnt work adding paket, please open in paket repo.

**Comment by aggieben** [comment]
@enricosada Ok.  It appears that the default template works as expected.  I'll open this on the paket repo.
