### ISSUE TITLE
unable to find Microsoft.NETCore.App

### ISSUE THREAD

**Issue by yawnt** [dotnet/netcorecli-fsc#119]
Hi everyone,

I'm running SDK version 2.0.0-preview3-25419-01, when I try to run `dotnet restore` I get the following.

```
error NU1102: Unable to find package Microsoft.NETCore.App with version (>= 2.0.0-preview3-25419-01)
error NU1102:   - Found 12 version(s) in nuget.org [ Nearest version: 2.0.0-preview1-002111-00 ]
```

I just ran this on a simple `dotnet new console -lang F#`
I'm running ArchLinux x86_64

Any idea? Thanks!

**Comment by yawnt** [comment]
Fixed by looking at https://github.com/dotnet/cli/issues/6730

added 
```
<add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
```

to ~/nuget/NuGet/NuGet.config

**Comment by jholovacs** [comment]
Where is this file?  I can't find anything remotely like it
