### ISSUE TITLE
add CI - Travis and/or Jenkins CI

### ISSUE THREAD

**Issue by enricosada** [dotnet/netcorecli-fsc#13]
There is a build script ( `build.cmd` ) and currently works with appveyor ci, but no webhook.

# CI

- [x] `dotnet-ci jenkins`. support all the os of sdk
- [ ] `travis`. useful for contributors and smoketest of the examples (user experience)
- [ ] `appveyor`. useful for contributors and smoketest of the examples (user experience)

# jenkins CI

following [onboarding steps](https://github.com/mmitche/dotnet-ci/blob/master/docs/CI-SETUP.md#onboarding-steps-for-your-project)

1. [x] send pr to dotnet/dotnet-ci to add this repo ( ref https://github.com/dotnet/dotnet-ci/pull/510 )
2. [x] make it accessibile to @dotnet-bot ( need admin, /cc @KevinRansom @jaredpar )
3. [x] configure webhooks ( need admin, @KevinRansom @jaredpar )
4. [x] add the jenkins build job def `netci.groovy`, following steps 4/5/6/7/8 as a PR 

# travis 

useful to run examples too, as smoketest of the experience of who use the sdk

1. [ ] webhook  ( need admin, ~~@KevinRansom~~ ~~@jaredpar~~)
2. [ ] create `.travis.yml`

# appveyor

useful to run examples too, as smoketest of the experience of who use the sdk

1. [ ] webhook  ( need admin, ~~@KevinRansom~~ ~~@jaredpar~~ )
2. [X] create `appveyor.yml`

**Comment by dsyme** [comment]
@enricosada As mentioned on slack, Linux CI is really important.

**Comment by mmitche** [comment]
@enricosada Please use these onboarding steps

https://github.com/mmitche/dotnet-ci/blob/master/docs/CI-SETUP.md

**Comment by dsyme** [comment]
@cloudRoutine may want to look into this

**Comment by enricosada** [comment]
@jared or @KevinRansom can you pls do the admin parts? 
i am not admin, so i cannot configure the webhooks needed for "build on commit/pr"

**Comment by cloudRoutine** [comment]
i've already setup the travis hook on my fork, so we can just check that until it's fixed on this repo

**Comment by enricosada** [comment]
@cloudRoutine nice, i have the appveyor configured in https://ci.appveyor.com/project/enricosada/netcorecli-fsc atm. so just a matter of webhooks

**Comment by enricosada** [comment]
waiting webhooks /cc @jaredpar @KevinRansom

**Comment by KevinRansom** [comment]
@Enrico Sada<mailto:enrico@sada.io>

You are on the admin team now.

Thanks

Kevin

**Comment by enricosada** [comment]
thx @KevinRansom

**Comment by enricosada** [comment]
@mmitche i added dotnet-ci and for pr works really well (copied the dotnet/cli flow). really fast.
But works only for pr, shouldnt works also for commits? i mean in https://github.com/dotnet/netcorecli-fsc/commits/master ? like https://github.com/dotnet/cli/commits/rel/1.0.0

**Comment by mmitche** [comment]
@enricosada https://github.com/dotnet/cli/blob/rel/1.0.0/netci.groovy#L10 CLI only generates jobs for isPR == true right now.  The check boxes come from internal builds.  You can generate the push jobs this way:

https://github.com/dotnet/buildtools/blob/master/netci.groovy#L13

Today it doesn't update the commit status (check boxes), but I'll look into that.  I think it's just a setting,

**Comment by enricosada** [comment]
Closing, using only dotnet ci because is awesome, no need for travis/appveyor atm

Supported os (both branch and PR testing), for release/debug configuration:

- Windows x64
- Ubuntu x64
- OS X
- RHEL 7.2
- Debian 8.2
- Fedora 23
- OpenSUSE 13.2
- CentOS 7.1

Added all badges in README

So i think we have a good linux testing coverage @dsyme :D

thx again to @mmitche for support
