### ISSUE TITLE
Support FSharp.Data on .Net Core

### ISSUE THREAD

**Issue by svick** [dotnet/netcorecli-fsc#16]
## Steps to reproduce
1. Run `dotnet new -l fs`.
2. Add dependency to `"FSharp.Data": "2.3.1"`.
3. `dotnet restore`, `dotnet build`
## Expected  behavior

`dotnet build` succeeds and I can then go on to use type providers from FSharp.Data.
## Actual behavior

`dotnet build` fails with:

> error FS3031: The type provider 'C:\Users\Svick\.nuget\packages\FSharp.Data\2.3.1\lib\portable-net45+netcore45\FSharp.Data.dll' reported an error: Assembly attribute 'TypeProviderAssemblyAttribute' refers to a designer assembly 'FSharp.Data.DesignTime' which cannot be loaded or doesn't exist. Could not load file or assembly 'FSharp.Data.DesignTime, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
> warning FS3005: Referenced assembly 'C:\Users\Svick\.nuget\packages\FSharp.Data\2.3.1\lib\portable-net45+netcore45\FSharp.Data.dll' has assembly level attribute 'Microsoft.FSharp.Core.CompilerServices.TypeProviderAssemblyAttribute' but no public type provider classes were found

Previously reported as https://github.com/dotnet/cli/issues/3776.

**Comment by rkeithhill** [comment]
I'm running into this very issue as well - trying to port an F# app onto .NET Core 1.0.

**Comment by nickolasacosta** [comment]
Update lib to .net core for Harambe

**Comment by enricosada** [comment]
the type providers are not supported atm in .net core.
more info in the issue discussion https://github.com/Microsoft/visualfsharp/issues/1496#issuecomment-244315047

**Comment by sphvn** [comment]
Would be very keen for this.

**Comment by TheAngryByrd** [comment]
I'd like to add, this error even comes up when `TargetFramework` is set to `net462`

```
<Project Sdk="FSharp.NET.Sdk;Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net462</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FSharp.Core" Version="4.1.*" />
    <PackageReference Include="FSharp.NET.Sdk" Version="1.0.*" PrivateAssets="All" />
    <PackageReference Include="FSharp.Data" Version="*"/>
    <DotNetCliToolReference Include="dotnet-mono" Version="0.1.2" />
  </ItemGroup>
</Project>
```

**Comment by Kurren123** [comment]
Hear hear. This is stopping us moving over.

**Comment by buvinghausen** [comment]
I was about to come post what @TheAngryByrd has posted this is definitely problematic

Same error message from @svick 

I can't live without the type providers and I really want to move everything over to .NET Core

**Comment by diegobfernandez** [comment]
I'm on the same boat as @TheAngryByrd. I just want to use the new format and target .NET Framework.
This is a little frustrating :/

**Comment by enricosada** [comment]
Closing as tracked in `Microsoft/visualfsharp` repo, more info in https://github.com/Microsoft/visualfsharp/issues/3069

> What about Type Providers and .NET Core?

> In theory, Erasing Type Providers will work on .NET Core 2.0 without any changes. @dsyme and @KevinRansom will be looking at this once the bits for .NET Core 2.0 and F# are stable enough. Generative Type Providers are cut for .NET Core right now. They take a dependency on System.Reflection.Emit, which has been cut for .NET Core 2.0 and .NET Standard 2.0. It's a high priority for the team who owns that library to make it available, though, and we help motivate that work. They will not begin until after .NET Core 2.0 ships, though.

**Comment by 7sharp9** [comment]
Cant a build for this be made with dotnetcore that simply has no TP's?

**Comment by victor-torres** [comment]
@diasbruno

**Comment by TheAngryByrd** [comment]
So if you want to get around this error now, there's a workaround https://github.com/Microsoft/visualfsharp/issues/3303
