### ISSUE TITLE
Add more template

### ISSUE THREAD

**Issue by aloisdg** [dotnet/netcorecli-fsc#21]
Hello,

I would enjoy to have the possiblity to do `dotnet new -l F# -t Lib` or `-t xunittest`. I think I could use [aspnet generator](https://github.com/OmniSharp/generator-aspnet), but I would prefer to use dotnet cli like I do in C#.

Thanks you for your work!

Cheers,

**Comment by odytrice** [comment]
I've been looking into this issue. I think you should raise it at dotnetcore cli repo https://github.com/dotnet/cli/issues I wasn't sure how to contribute it there that's why I did the added it to the aspnet generator instead.

**Comment by enricosada** [comment]
Logged into another issue

Closing as dupe of #36
