### ISSUE TITLE
Basic support for msbuild fsproj

### ISSUE THREAD

**Issue by enricosada** [dotnet/netcorecli-fsc#23]
## GOAL

The sdk cli experience is fully supported xplat for .net core only projects, and the only requirement is the .net core sdk installed.

The IDE experience is VS Code, and **doesnt require mono** for ionide on osx/linux
fsharp interactive works after is installed.
Tutorials show basic usage for console/lib and for add support to existing projects 
Docker works like for normal .net sdk project
Debuggin works inside VS Code

## TODO

- Xplat development on cli with .net core sdk only installed.
- IDE supported: VS Code (`restore`, `build`, `run`) and intellisense. mono installed is **not** required for Ionide
- VS Code support debugging
- Templates: `console`, `lib`, `xunit`, `nunit`, `suave`, `aspnetcore`
- All sdk commands supported (`new`,`restore`,`build`,`run`,`pack`,`publish`,`test`)
- Tutorial:
    - how to add netstandard support into existing nuget package
    - from zero to a library package ( `netstandard1.6` )
    - from zero to .net core console app ( `netcoreapp1.0` )
- fsharp interactive, installed as sdk tool/command (`dotnet fsi`)
- Docker examples (`console`),, but should be enough the doc for normal .net sdk projects

## For dev:

- CI on all supported os
- CI on travis/appveyor
- Test suite of all sdk commands:
    - `netstandard1.6`/`netcoreapp1.0`
- xplat .NET Core toolchain: `FCS` (and deps), `FSAC.Suave`, if possibile

## Reality check

Works for project already using `preview2`, and remove some pain
Enable used tools/lib in F# ecosystem to go xplat (note: type providers are not supported)

Various project to add or enhance .net core (or sdk) support.

| Project            | Who               | PR | 
|----------------|-----------------|----|
| Paket              | @forki             | https://github.com/fsprojects/Paket/pull/1977 |
| FAKE               | @matthid       | https://github.com/fsharp/FAKE/pull/1281  |
| ASP.NET Core | @neoeinstein |  |

Some projects already works in `preview2`, so no source code changes are expected.
The published packages are already ok (`netstandard1.6`), no need to change these because can be used in `preview3`.
Expected changes of migration `preview2` -> `preview3` are only:
- `project.json` -> `fsproj`
- infra (build script) 
- docs

| Project            | Who               | PR | 
|----------------|-----------------|----|
| Suave             | @enricosada   | | 
| Argu               |                        | |
| Chessie          |                         | |
| FsCheck         |                         | |
| FCS                |                         | |

**Comment by enricosada** [comment]
Create separate issues:

- use msbuild task instead of `dotnet-compile-fsc` 
- add `dotnet new` templates to `dotnet/cli` (with `-*` so can be fixed later if needed)
- report/fix errors (see test suite)
- should work with current published (same as `preview2`) `FSharp.Core` and compiler package
- check latest `FSharp.Core` and compiler package deps (no private dev deps if not required)
- dotnet `restore`/`build`/`run`/`pack`/`publish`/`test` tests
  - Support for .net core (`netcoreapp1.0`) and .net standard (`netstandard1.6`)
- use `msbuild` for smoke tests
- use `dotnet test` + `xunit` for all other tests

**Comment by cloudRoutine** [comment]
@matthid has been working on the netcore FAKE

@kurtschelfthout how much needs to be done for FsCheck to be netcore ready?

**Comment by cloudRoutine** [comment]
We could also use a [github project](https://github.com/dotnet/netcorecli-fsc/projects) to organize this.

[I've found them to be useful](https://github.com/fsharp-editing/ProtoWorkspace/projects/1)

**Comment by kurtschelfthout** [comment]
@cloudRoutine None as far as I'm aware, it supports profile259 already. There is also https://github.com/fscheck/FsCheck/pull/293

**Comment by matthid** [comment]
yep, put me up for FAKE. (pr on my branch is welcome as well ;))

**Comment by enricosada** [comment]
@kurtschelfthout @cloudRoutine i added a comment in https://github.com/fscheck/FsCheck/pull/293#issuecomment-261278407 . portable259 is ok, but i think there are issue with `dotnet test` using that (or maybe was a transitory issue resolved already)

**Comment by enricosada** [comment]
Closing, all project listed support `netstandard1.6` now and further issues are tracked in specific repo

The development story works for multiple editors
