### ISSUE TITLE
Support for crossgen in msbuild fsproj

### ISSUE THREAD

**Issue by enricosada** [dotnet/netcorecli-fsc#24]
## GOAL

The .NET Core Sdk can be used as replacement of old fsproj for normal development.

Support crossgen (multiple target frameworks in same project), the new fsproj can produce console/nugetpackage for multiple frameworks (.net fw, pcl, netcore).
The sdk cli experience is fully supported.
VS Code require mono installed in osx/unix and .net full on windows (because net461 project can use type provider, and current `netcoreapp1.0` `fsc` compiler cannot do that).
Make it easy to migrate from old fsproj -> msbuild 15 fsproj for .net core sdk
The merge of packages (.net fw and netcore) is not needed anymore
The `dotnet test` test runner works in IDEs

## TODO

- Test suite of all sdk commands:
  - crossgen (`net451` + `netstandard`/`netcoreapp` + `pcl`)
- https://github.com/ionide/ionide-vscode-fsharp/issues/278 VS Code support for multi targeting (can switch current target)
- Paket is supported
- IDE supported: VS
- IDE supported: Xamarin studio

**Comment by stephan-tolksdorf** [comment]
@enricosada Is it possible to target PCL 259, i.e. `portable-net45+win8+wpa81+wp8`, using the new SDK? Could you maybe point me to an example fsproj file?

**Comment by enricosada** [comment]
@stephan-tolksdorf new sdk doesnt support creation of portable profiles. MS deprecated these in favor of netstandard.

**Comment by enricosada** [comment]
closing as supported from cli.
VS and VSCode are tracked in respective repo
