### ISSUE TITLE
Use `Fsc` msbuild task instead of `dotnet-compile-fsc`

### ISSUE THREAD

**Issue by enricosada** [dotnet/netcorecli-fsc#25]
The msbuild target invoke the `dotnet-compile-fsc` sdk tool.
Should use an `Fsc`  msbuild task instead (see microsoft/visualfsharp task for example)

**Comment by enricosada** [comment]
integration should be like now, so target file are good or similar.
But instead of call `dotnet-compile-fsc` [in the target file](https://github.com/dotnet/netcorecli-fsc/blob/99e22f5413fa0dc7ea16bf92a35fb0048fa99207/src/FSharp.NET.Sdk/FSharp.NET.Core.Sdk.targets#L141) , we use `Fsc` task.

`Fsc` task source code i think can be duplicated (for now) from `microsoft/visualfsharp` repo.
Later it should use the fsc task from visualsharp as deps, on just one package (doenst matter from what repo) with embedded assembly/target

The f# target files pratically set properties of `Fsc` task in `CoreCompile` target.

the `Fsc` task should contains the same little workaround of `dotnet-compile-fsc` (.exe extension, `--targetprofile`, etc), if needed. 
Maybe .exe is not required anymore with newer compiler version

**Comment by cloudRoutine** [comment]
Is the FSC task going to be bundled with the target files in the `FSharp.NET.Sdk` nupkg?

**Comment by enricosada** [comment]
yes, temporary.
we make it work, and after we can coordinate/sendpr to microsoft/visualfsharp

**Comment by enricosada** [comment]
fixed by #61
