### ISSUE TITLE
Align to latest .net core sdk preview3 build

### ISSUE THREAD

**Issue by enricosada** [dotnet/netcorecli-fsc#26]
Continue align to latest .net core sdk preview3 build

- test suite
- add workaround if needed
- add docs about workaround

**Comment by cloudRoutine** [comment]
[Since preivew4 is out now](https://github.com/dotnet/cli#installers-and-binaries) should we align to that instead?

**Comment by enricosada** [comment]
we should make it work on `preview3` first, that's the first stable published.
and start check preview4 too.

that's easy because we just change `dotnet` in `PATH` 😄 
and maybe package version inside tests (but these are already in a .props file, easy to override from command line)

**Comment by enricosada** [comment]
closing becasue `master` is now is aligned with current released `preview3`
