### ISSUE TITLE
App to migrate from old fsproj -> msbuild 15 fsproj

### ISSUE THREAD

**Issue by enricosada** [dotnet/netcorecli-fsc#30]
console app to migrate from old fsproj -> msbuild 15 fsproj for .net core sdk
Paket aware

### Microsoft.NET.Sdk Targets Reference

- [Microsoft.NET.Sdk.targets](https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/buildCrossTargeting/Microsoft.NET.Sdk.targets)
- [Signing.Imports.targets](https://github.com/dotnet/sdk/blob/master/build/Targets/Signing.Imports.targets)
- [Microsoft.NET.GenerateAssemblyInfo.targets](https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.GenerateAssemblyInfo.targets)
- [Microsoft.NET.Publish.targets](https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Publish.targets)
- [Microsoft.NET.Sdk.BeforeCommon.targets](https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.BeforeCommon.targets)
- [Microsoft.NET.TargetFrameworkInference.targets](https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.TargetFrameworkInference.targets)
- [Microsoft.NET.DisableStandardFrameworkResolution.targets](https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.DisableStandardFrameworkResolution.targets)
- [Microsoft.NET.DefaultOutputPaths.targets](https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.DefaultOutputPaths.targets)
- [Microsoft.NET.Sdk.Common.targets](https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.Common.targets)
- [Microsoft.NET.Sdk.targets](https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.targets)
- [Microsoft.NET.RuntimeIdentifierInference.targets](https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.RuntimeIdentifierInference.targets)
- [Microsoft.PackageDependencyResolution.targets](https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.PackageDependencyResolution.targets)

**Comment by cloudRoutine** [comment]
So we should base it on these?
- [dotnet-migrate](https://github.com/dotnet/cli/tree/rel/1.0.0/src/dotnet/commands/dotnet-migrate)
- [Microsoft.DotNet.ProjectJsonMigration](https://github.com/dotnet/cli/tree/rel/1.0.0-preview3/src/Microsoft.DotNet.ProjectJsonMigration)
- [Microsoft.DotNet.ProjectJsonMigration.Tests](https://github.com/dotnet/cli/tree/rel/1.0.0/test/Microsoft.DotNet.ProjectJsonMigration.Tests)
- [ProjectJsonToCSProj.md](https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/ProjectJsonToCSProj.md)


Some questions -
- Is this a normal console app or a dotnet extensibility console app designed to be used with the dotnet cli?
- Is this app going to live in this repo?
- Is it going to be published as a nuget package?

**Comment by enricosada** [comment]
As a precisation: this issue is old fsproj, not `project.json`. There is #38 for project.json -> fsproj

About oldfsprj -> newfsproj

Dunno if is a supported scenario in dotnet/cli (i think not) but more an xamaringstudio/vs thing (csproj was never supported in dotnet/cli)
Probably is ok to be a console app. but we need to check if there is already an effort by dotnet team about that, and use that. @piotrpMSFT @cartermp got info about this scenario?

**Comment by enricosada** [comment]
Added `up-for-grab` label.

A normal console app, just `xml -> xml` tool. For console and lib project (lib is more important)

So from a standard fsproj lib (see existing project or VS new f# templates) to a netcore fsproj (see templates).
- useful if just create a `netstandard` so is easier to add netcore to existing projects
- best if can create crossgen project `<TargetFrameworks>net451;netstandard1.6</TargetFrameworks>` too but v2.

**Comment by cartermp** [comment]
@enricosada I'm not entirely sure about this scenario, but I think a console app is ok.

**Comment by enricosada** [comment]
closing as extenal
