### ISSUE TITLE
Support new templating engine of sdk `dotnet new`

### ISSUE THREAD

**Issue by enricosada** [dotnet/netcorecli-fsc#31]
The `dotnet new` will support remote packages (from nuget feeds) using the [dotnet/templating](https://github.com/dotnet/templating) library.

more info in the library repository

- Support all current existing netcore F# templates
- Check if partial templates are supported
- Write tutorial about adding new templates
- Support common .net core ready scenario:
    - console app: `console` + `argu`
    - dotnet test with fscheck: `console` + `xunit` + `fscheck`

**Comment by cloudRoutine** [comment]
Are all of these templates going to be packaged together in a `nupkg` that lives in this repo?

**Comment by enricosada** [comment]
no, from nuget feed, so we will publish templates on nuget.org (or another feed)
i dunno spec atm, one package per template type? dunno
but idea is no more embedding inside repo

**Comment by cloudRoutine** [comment]
i should have been more specific, I meant the src would live in the repo, not that the packages would be hosted and downloaded from here 😄

**Comment by enricosada** [comment]
different packages for sdk an templates.
about sources, i hope to move where can be maintained by authors (xunit in xunit repo etc).

**Comment by cloudRoutine** [comment]
You really think they'll do that? I don't think people like having extra tedious work dropped on them, especially to support a programming language they don't use.

I think it'd find a more attentive home at at https://github.com/fsharp-editing or https://github.com/fsharp instead

**Comment by enricosada** [comment]
depends. Template are stupid, usually is just changing the package version after the first contribution. source code doesnt change a lot.
And anyway, we can maintain these in the repositories of authors, sending pr. 
As a note, xunit author tried f# and added also `async` support 😄

**Comment by enricosada** [comment]
ok now all templates are moved outside `dotnet new` in `dotnet new3`, and source files are in https://github.com/dotnet/templating/tree/master/template_feed

with new rc4 the `dotnet new3` become `dotnet new`

**Comment by enricosada** [comment]
Closing.

All previous `dotnet new` template are already moved inside https://github.com/dotnet/templating ( thx @mlorbetske about that).

Library maintainers can see https://github.com/dotnet/templating about how to add new templates.
