### ISSUE TITLE
The fsharp compiler `fsc` should be an sdk tool

### ISSUE THREAD

**Issue by enricosada** [dotnet/netcorecli-fsc#32]
If the compiler is a tool:

- xplat ready
- it's anyway already inside a nuget package, but not easy to restore
- easy to run as `dotnet fsc`
- easier to run from msbuild task (just run `dotnet fsc`)
- can be specified by project:
    - projects can use different compiler versions, or the same
    - easy development/test of compiler, just change version and restore from dir

Require:

- https://github.com/dotnet/cli/issues/4722 - `dotnet/cli` drop `dotnet-` prefix requirement for .net tools 
- `fsc` as a normal console `netcoreapp1.0`

**Comment by cloudRoutine** [comment]
@enricosada what's the status on this?

**Comment by enricosada** [comment]
Closing becuase dotnet/cli#4722 (prerequisite) is moved to at least sdk v2.0.
Can be reopened when its implemented, or the cli tools constraints are changed.

Atm fsc will be published as framework dependent deployment, and packaged like [FSharp.Compiler.Tools](https://www.nuget.org/packages/FSharp.Compiler.Tools/)
