### ISSUE TITLE
FSharp Interactive (fsi) as a sdk tool

### ISSUE THREAD

**Issue by enricosada** [dotnet/netcorecli-fsc#34]
The .net sdk tools give lot of benefits:

- xplat ready (are just `netcoreapp1.0` console app)
- no boostrapping issues (are downloaded on `dotnet restore` step)
- easy discoverability (`dotnet fsi`)
- is a shared app, so minimal size (no coreclr, use installed runtime)
- fsi version can be changed just changing the package version (or pinned to a specific version)

And `fsi` as normal netcore console app give others:
- can be published as standalone, so contains coreclr/everything per os, so just `fsi` (or `fsharpi`)
- easy to package per os

Blockers:

- https://github.com/dotnet/cli/issues/4722 atm .net cli require `dotnet-` prefix for tools, so a wrapper is needed (useless) or rename (annoying)

**Comment by enricosada** [comment]
Not next preview4, but the one after will support global commands. 
So fsi can be installed once like `dotnet install fsi --global` , and works with `dotnet fsi` or maybe directly `fsi`

**Comment by matthid** [comment]
> Not next preview4, but the one after will support global commands.

@enricosada can you provide more information about this? (A link for example?)

**Comment by enricosada** [comment]
closing as tracked in visualfsharp repo, ref https://github.com/Microsoft/visualfsharp/issues/3069
