### ISSUE TITLE
Debugging inside VS Code

### ISSUE THREAD

**Issue by enricosada** [dotnet/netcorecli-fsc#35]
Debugging of .net core console app (`netcoreapp1.0`) works inside VS Code

Like c# now using c# extension or ominisharp

- breakpoints
- `F5` run in debug
- watch

## TODO

- compiler emit pdb in portable pdb format
- vscode debugging engine recognize f# console and pdb

**Comment by cloudRoutine** [comment]
To get debugging functionality in vscode we'd need to implement [the debugging api protocol](https://code.visualstudio.com/docs/extensionAPI/api-debugging) in either a standalone extension or directly into [ionide-vscode-fsharp](https://github.com/ionide/ionide-vscode-fsharp), I think we should put it straight into Ionide.

Reference -
- [omnisharp-vscode : debugger.md](https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger.md)
- [omnisharp-vscode : coreclr-debug](https://github.com/OmniSharp/omnisharp-vscode/tree/master/src/coreclr-debug)
- [coreclr-debug-win7-x64.zip](https://vsdebugger.azureedge.net/coreclr-debug-1-5-0/coreclr-debug-win7-x64.zip) 
- [ omnisharp slack team signup form](https://docs.google.com/forms/d/e/1FAIpQLSec8LD9VRIej6KNJH6ckTXF40mKfqSKemsyf8xDHU7PwLh-sg/viewform) - they've been helpful whenever I've gone to them with question in the past

**CC** @Krzysztof-Cieslak @7sharp9 @vasily-kirichenko

**Comment by Krzysztof-Cieslak** [comment]
I think omnisharp should put their debugger in extension and add F# to it. Just like mono-debugger

**Comment by cloudRoutine** [comment]
@Krzysztof-Cieslak cool, then you should [sign up for their slack](https://docs.google.com/forms/d/e/1FAIpQLSec8LD9VRIej6KNJH6ckTXF40mKfqSKemsyf8xDHU7PwLh-sg/viewform) and discuss how to make that work with them.

**Comment by enricosada** [comment]
closing in favor of https://github.com/ionide/ionide-vscode-fsharp/issues/366

let's discuss where is developed
