### ISSUE TITLE
fsproj vNext Project Inspector

### ISSUE THREAD

**Issue by cloudRoutine** [dotnet/netcorecli-fsc#40]
Standalone tool similar to the FSharp.Compiler.Service ProjectCracker for reading the project options out of  the new msbuild format for netcore

### In Progress 

- [fsprojectile](https://github.com/fsharp-editing/fsprojectile)

**Comment by enricosada** [comment]
done with https://github.com/enricosada/dotnet-proj-info
and integrated in FSAC with https://github.com/fsharp/FsAutoComplete/issues/137
works in latest ionide/vim already
