### ISSUE TITLE
Split `FSharp.NET.Sdk` package in sdk only + targets

### ISSUE THREAD

**Issue by enricosada** [dotnet/netcorecli-fsc#56]
ref dotnet/cli#4976

Move `Sdk` dir in another `FSharp.NET.Sdk` package version, so can be bundled in VS/cli

- `FSharp.NET.Sdk` `1.0.0-bundled` the part bundled in VS/cli
- `FSharp.NET.Sdk` `1.0.0` the part restored from PackageReference

Name cannot be changed atm (will break templates, so lot of pain), so atm using two version can be ok (the -`bundled` is pinned anyway in VS/CLI).

**Comment by piotrpMSFT** [comment]
👀 

I hope all is well in F#!

**Comment by enricosada** [comment]
@piotrpMSFT yes, the sdk part was ok, i was finishing the package (removing dotnet-compile-fsc, some cleanup, etc)
i'll fix this with dotnet/cli#5557  and more PR with new templates soon (probably i need to learn about `dotnet new3` too for that 😄 )

**Comment by enricosada** [comment]
moved to .net core sdk 2.0, the 1.0 is code freeze
