### ISSUE TITLE
dotnet-compile-fsc

### ISSUE THREAD

**Issue by ncave** [dotnet/netcorecli-fsc#6]
@enricosada I noticed that using the latest dotnet cli on an clean slate (empty nuget cache and no packages), doing dotnet restore on a new F# project does not pull the dotnet-compile-fcs and does not create the .tools in the .nuget/packages folder.
But, if I dotnet restore netcorecli-fsc first, then go back to the F# app, it now starts working as expected (pulls dotnet-compile-fsc, creates .tools, etc).
Any idea what dependency is missing in the template for a new F# core app?

**Comment by enricosada** [comment]
maybe you need a feed, ref https://github.com/dotnet/cli/issues/2384

You can use [last known good version](https://github.com/enricosada/fsharp-dotnet-cli-samples/wiki/Status#last-known-good-version), that work for develop .net core libraries/app

**Comment by ncave** [comment]
Thanks! The workaround with restoring netcorecli-fsc first works too for now.
