### ISSUE TITLE
Multiple embedded resources issue

### ISSUE THREAD

**Issue by ncave** [dotnet/netcorecli-fsc#74]
Using a simple starter template:

```xml
<Project Sdk="FSharp.NET.Sdk;Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard1.6</TargetFramework>
    <Version>1.0.0-alpha</Version>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Library.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FSharp.NET.Sdk" Version="1.0.*" PrivateAssets="All" />
    <PackageReference Include="FSharp.Core" Version="4.1.*" />
  </ItemGroup>
</Project>
```
Adding more than one .resx file to the folder results in the following build error:
```
C:\Program Files\dotnet\sdk\1.0.0-rc4-004771\Microsoft.Common.CurrentVersion.targets(2857,5): error MSB3577: Two output file
 names resolved to the same output path: "obj\Debug\netstandard1.6\.resources" [C:\Projects\test_fs\test_fs.fsproj]
```
P.S. C# templates work fine with multiple .resx

**Comment by enricosada** [comment]
@ncave the resx where not converted to resource files at all 😄 now is implemented

**Comment by ncave** [comment]
@enricosada More than one .resx file in project works now?

**Comment by enricosada** [comment]
@ncave yes, because resx was not implemented at all, so all resx collided to `obj\Debug\netstandard1.6\.resources` instead of obj\Debug\netstandard1.6\Res1.resources` for `Res1.resx` etc

i just need to publish `FSharp.NET.Sdk` 1.0.1 on nuget.org (really soon, probably tonight), i'll ping you and in the https://github.com/fsharp/FSharp.Compiler.Service/issues/700 issue

**Comment by ncave** [comment]
Would it work with other target frameworks too (net462)?

**Comment by enricosada** [comment]
good test case.
Anyway yes, checked. i'll add to test suite (i need to use a better framework matrix, or anyway cleanup a bit)

**Comment by enricosada** [comment]
@ncave just to be sure i added as tests in https://github.com/dotnet/netcorecli-fsc/pull/82. 

if you have more test case in mind np, but there is just invocation of task built by vf# repo, but no need to duplicate testing a lot (but check target framework is ok ihmo)

**Comment by enricosada** [comment]
@ncave this issue is fixed with the new published [FSharp.NET.Sdk v1.0.1 package](https://www.nuget.org/packages/FSharp.NET.Sdk/1.0.1)

**Comment by ncave** [comment]
Thanks!
