### ISSUE TITLE
Add mono in CI

### ISSUE THREAD

**Issue by enricosada** [dotnet/netcorecli-fsc#78]
add mono (latest) to ci. The one used in vNext of VS on Mac.

@mmitche the dotnet-ci support mono? have it installed in some build image i can add to current job matrix? /cc @mrward @nosami 

plan B: travisci, if support latest mono

**Comment by mmitche** [comment]
@enricosada Yeah, it's installed on many images, though not all.  I think it's 4.6.2  What are you looking for?

**Comment by enricosada** [comment]
@mrward @nosami i really need a CI server somehow, i am now manually testing on azure vm, but is not the best. As a note the solution applyed here can be used also for visualfsharp repo, because they have the same issue moving forward /cc @cartermp @KevinRansom @dsyme .

@mmitche what i need is the latest alpha of mono (so 5.0.0.*), other teams doesnt have a similar situation? maybe a build worker with mono nightly (or alpha) installed?
Other possibile way to do it is `apt install mono-dev` in the docker container job maybe? i think i have two of these. but it will be slower

**Comment by nosami** [comment]
I think the easiest way would be to use an OSX worker on travis and install a mono .dmg on there

**Comment by nosami** [comment]
@enricosada: something like this http://stackoverflow.com/a/16946955/316874

**Comment by enricosada** [comment]
last time i checked travis was not enabled in this dotnet org.
i have seen a notification about appveyor was enabled.
but let me check

**Comment by mmitche** [comment]
@enricosada Is this a nightly shifting version of mono? On Linux only or OSX too?

**Comment by enricosada** [comment]
@mmitche i think the [latest mono alpha](http://www.mono-project.com/download/alpha/#download-lin) can be enough if is possibile to have always the alpha (current `5.0 Alpha 3 (5.0.0.61)` is bugged for my usage, but next drop will be ok hopefully).
Having a `nightly` may help to prevent regressions (already happened, that's why i'd like mono on CI)
but @nosami @mrward can help more about choosing the right target.

Is ok for linux only (or mac, what's easiest), i just like to have at least one mono 5.0.* on CI

**Comment by mmitche** [comment]
@enricosada Are you running your testing in a docker container?  IMO, I believe on Linux, you should be able to simply apt-get the package in the beginning of your CI process.  On mac this is more difficult because we need to be able to remove the packages after the run.

**Comment by mmitche** [comment]
@enricosada The only thing we might need to change over is to an image that doesn't require a password for sudo so that the package installs properly.

**Comment by mmitche** [comment]
@enricosada Last question, this is only ubuntu...or...?

**Comment by enricosada** [comment]
ubuntu ok

**Comment by mmitche** [comment]
kk.  And to install mono-dev...do I need to add a new package feed (sorry for all the questions)

**Comment by enricosada** [comment]
@mmitche i followed the instruction in http://www.mono-project.com/download/alpha/#download-lin for Ubuntu 14.04.

so there is also

```
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
echo "deb http://download.mono-project.com/repo/ubuntu alpha-trusty main" | sudo tee /etc/apt/sources.list.d/mono-official-alpha.list
sudo apt-get update
```

and after `sudo apt-get install mono-devel` was ok

**Comment by enricosada** [comment]
And np about all the questions. Thanks a lot for help!

**Comment by mmitche** [comment]
awesome.  Okay i'm going to add a new VM template that will install the latest.  This isn't our desired state in the end, but it's a stopgap to solve the immediate issue.  Better VM desired state is being worked on next sprint.  We could potentially also use docker for this long-term.

**Comment by enricosada** [comment]
Awesome!
dunno if is easier, but nosami previously commented about osx and dmg in https://github.com/dotnet/netcorecli-fsc/issues/78#issuecomment-297450890 . maybe is easier or not.


Thank a LOT for help!

**Comment by mmitche** [comment]
@enricosada Testing it manually right now.

**Comment by mmitche** [comment]
@enricosada Okay.  I think I got it.  Should we enable this as an additional build platform for the CI in this repo?

**Comment by enricosada** [comment]
yes, how can i do that?

**Comment by enricosada** [comment]
Closing, development is moving to `microsoft/visualfsharp` repo, ref https://github.com/dotnet/netcorecli-fsc/issues/115

Testing is done manually atm, test suite already support it.
