### ISSUE TITLE
Error in output

### ISSUE THREAD

**Issue by Alxandr** [dotnet/netcorecli-fsc#8]
I'm getting some rather weird output when compiling. Things doesn't come in the correct order.

![image](https://cloud.githubusercontent.com/assets/112334/14953545/f79d7dee-106a-11e6-9533-03a350287064.png)

**Comment by enricosada** [comment]
Thx @Alxandr 
It's the same as https://github.com/dotnet/cli/issues/2333 not fixed yet

**Comment by dsyme** [comment]
@enricosada reports that this is fixed when using .NET Core  preview 3

**Comment by enricosada** [comment]
fixed in `preview3` using msbuild
