### ISSUE TITLE
Can't build ASP.NET Core MVC with F# in Ubuntu 16.10

### ISSUE THREAD

**Issue by ridderholt** [dotnet/netcorecli-fsc#91]
Sorry if this isn't the correct repo to ask this question in, please let me know if I should report it elsewhere.

Yesterday I installed the latest version of .NET Core on Linux (Ubuntu 16.10) and started with trying to create a new MVC app using F#.

I created a new project `dotnet new mvc -lang F#` and ran `dotnet restore`
But when I tired to run it using `dotnet run` or `dotnet build` I get this error
```
/home/robin/.nuget/packages/fsharp.net.sdk/1.0.1/build/FSharp.NET.Core.Sdk.targets(170,9): error MSB6006: "dotnet" exited with code 131. [/home/robin/Workspace/Labb/FSharpMVC/FSharpMVC.fsproj]
```

Maybe it's a newbie error and I have forgotten to install something but I can't figure out what to do. Any ideas?

**Comment by enricosada** [comment]
@ridderholt it's ok to file there 😄 

Can you please:

- run `dotnet --info`
- run build with `dotnet build -v n` to show diagnostic info (`-v` is the verbose argument), i am interested in dotnet invocation like `/path/to/dotnet  "~/.nuget/packages/fsharp.compiler.tools/4.1.0/build/netcoreapp1.0/fsc.dll" -o:ob...` if you can also rerun that from shell will show more error


meanwhile i'll try with 16.10 (i have 16.04 in ci tests)

**Comment by enricosada** [comment]
as a note, from https://github.com/dotnet/core/issues/532#issuecomment-285057524 probably is not specific to mvc template

@ridderholt you get same error with console template ( `dotnet new console -lang f#` ) ?

**Comment by enricosada** [comment]
added this https://github.com/dotnet/netcorecli-fsc/wiki/.NET-Core-SDK-1.0.1#ubuntu-1610-fails-to-build-projects as known issues in wiki

**Comment by kontomondo** [comment]
@ridderholt @enricosada I also had the same error, and after installing the 1.0.4 SDK (targeted for 16.04)  it works just fine. So @ridderholt you may want to try that as a workaround.

**Comment by enricosada** [comment]
@kontomondo yes please just the `dotnet --info` of working and not working if possible. 
Maybe 16.10 doesn't have .net core 1.0 runtime installed, but just 1.1. Can you check the sdk subdir where is installed dotnet?

**Comment by kontomondo** [comment]
@enricosada even without doing the info (will submit shortly) I can already tell you that the 16.04 version has both 1.0 and 1.1 and 16.10 has only 1.1. As I remember it seemed odd to me at the time. The download for 16.10 is also 35mb smaller. 

Btw, I wanted to edit the wiki page to submit a PR for it, but it seems to have saved my edit, probably the permissions for the wiki are too broad ? Please feel free to revert my change if you feel it's not good.

**Comment by kontomondo** [comment]
@enricosada the two versions have identical output for --info:
```
./dotnet --info
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.10
 OS Platform: Linux
 RID:         ubuntu.16.10-x64
```
With only Base Path differs (but points to sdk/1.0.1)

**Comment by ridderholt** [comment]
@enricosada Yes I get the same error when compiling an F# console app.

Here's the output when I run `dotnet --info`
```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.10
 OS Platform: Linux
 RID:         ubuntu.16.10-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.1
```

**Comment by ridderholt** [comment]
@enricosada I wasn't quite sure what you meant with 

>  run build with dotnet build -v n to show diagnostic info (-v is the verbose argument), i am interested in dotnet invocation like /path/to/dotnet "~/.nuget/packages/fsharp.compiler.tools/4.1.0/build/netcoreapp1.0/fsc.dll" -o:ob... if you can also rerun that from shell will show more error

but i ran `dotnet build -v n | grep -a "fsc.dll"` and this is my output:
```
/usr/share/dotnet/sdk/1.0.1/Sdks/../../../dotnet  "/home/robin/.nuget/packages/fsharp.compiler.tools/4.1.0/build/netcoreapp1.0/fsc.dll" -o:obj/Debug/netcoreapp1.1/FSharpMVC2.dll
```
Let me know if you want something else!

**Comment by AndrewSav** [comment]
Last time, where [f# did not work out of the box](https://github.com/dotnet/netcorecli-fsc/issues/42) took about a month and a half to fix, but hey, better late than never. I'm posting this to set expectation to those who have the same issue and stumble on this thread: a bit of patience, and we'll get there ;)

**Comment by AndrewSav** [comment]
In the ways of improvements,  I'd also suggest a better error message than `"dotnet" exited with code 131`

**Comment by dee-see** [comment]
@AndrewSav That's not very encouraging to read only 9 hours after it has been posted, but thanks for the info nonetheless. ;)

**Comment by kontomondo** [comment]
@dee-see @AndrewSav as I mentioned in this thread previously, there's a trivial workaround, the 16.04 download works perfectly well on 16.10 and it supports both netcore 1.0 and 1.1

**Comment by AndrewSav** [comment]
@kontomondo this issue is not specific for ubuntu, the same issues is on Fedora too. But there are now sdk for Fedora on that page, so the work around unfortunately is not so trivial.

**Comment by zunder** [comment]
Can't build an F# project either. The trivial proposal of installing a package above does not apply in my case, as I am running an Arch distro.

Is there any progress on this issue? Are there any other solutions rather than installing an older versions?

Here is my system info and the error I am getting:

```
> dotnet

Microsoft .NET Core Shared Framework Host

  Version  : 1.1.0
  Build    : 928f77c4bc3f49d892459992fb6e1d5542cb5e86
```
```
> dotnet --info

.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     manjaro
 OS Version:  
 OS Platform: Linux
 RID:         ubuntu.16.10-x64
 Base Path:   /opt/dotnet/sdk/1.0.1
```
```
> dotnet build -v n

Microsoft (R) Build Engine version 15.1.548.43366
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 4/22/17 2:38:20 PM.
     1>Project "/home/alex/dotnet/dotnet.fsproj" on node 1 (Build target(s)).
     1>CoreCompile:
         /opt/dotnet/sdk/1.0.1/Sdks/../../../dotnet  "/home/alex/.nuget/packages/fsharp.compiler.tools/4.1.1/build/netcoreapp1.0/fsc.dll" -o:obj/Debug/netcoreapp1.1/dotnet.dll
         -g
         --debug:portable
         --noframework
         --define:DEBUG
         --define:NETCOREAPP1_1
         --optimize-
         -r:/home/alex/.nuget/packages/fsharp.core/4.1.12/lib/netstandard1.6/FSharp.Core.dll
         -r:/home/alex/.nuget/packages/microsoft.csharp/4.3.0/ref/netstandard1.0/Microsoft.CSharp.dll
         -r:/home/alex/.nuget/packages/microsoft.visualbasic/10.1.0/ref/netstandard1.1/Microsoft.VisualBasic.dll
         -r:/home/alex/.nuget/packages/microsoft.win32.primitives/4.3.0/ref/netstandard1.3/Microsoft.Win32.Primitives.dll
         -r:/home/alex/.nuget/packages/system.appcontext/4.3.0/ref/netstandard1.6/System.AppContext.dll
         -r:/home/alex/.nuget/packages/system.buffers/4.3.0/lib/netstandard1.1/System.Buffers.dll
         -r:/home/alex/.nuget/packages/system.collections.concurrent/4.3.0/ref/netstandard1.3/System.Collections.Concurrent.dll
         -r:/home/alex/.nuget/packages/system.collections/4.3.0/ref/netstandard1.3/System.Collections.dll
         -r:/home/alex/.nuget/packages/system.collections.immutable/1.3.0/lib/netstandard1.0/System.Collections.Immutable.dll
         -r:/home/alex/.nuget/packages/system.componentmodel.annotations/4.3.0/ref/netstandard1.4/System.ComponentModel.Annotations.dll
         -r:/home/alex/.nuget/packages/system.componentmodel/4.3.0/ref/netstandard1.0/System.ComponentModel.dll
         -r:/home/alex/.nuget/packages/system.console/4.3.0/ref/netstandard1.3/System.Console.dll
         -r:/home/alex/.nuget/packages/system.diagnostics.debug/4.3.0/ref/netstandard1.3/System.Diagnostics.Debug.dll
         -r:/home/alex/.nuget/packages/system.diagnostics.diagnosticsource/4.3.0/lib/netstandard1.3/System.Diagnostics.DiagnosticSource.dll
         -r:/home/alex/.nuget/packages/system.diagnostics.process/4.3.0/ref/netstandard1.4/System.Diagnostics.Process.dll
         -r:/home/alex/.nuget/packages/system.diagnostics.tools/4.3.0/ref/netstandard1.0/System.Diagnostics.Tools.dll
         -r:/home/alex/.nuget/packages/system.diagnostics.tracing/4.3.0/ref/netstandard1.5/System.Diagnostics.Tracing.dll
         -r:/home/alex/.nuget/packages/system.dynamic.runtime/4.3.0/ref/netstandard1.3/System.Dynamic.Runtime.dll
         -r:/home/alex/.nuget/packages/system.globalization.calendars/4.3.0/ref/netstandard1.3/System.Globalization.Calendars.dll
         -r:/home/alex/.nuget/packages/system.globalization/4.3.0/ref/netstandard1.3/System.Globalization.dll
         -r:/home/alex/.nuget/packages/system.globalization.extensions/4.3.0/ref/netstandard1.3/System.Globalization.Extensions.dll
         -r:/home/alex/.nuget/packages/system.io.compression/4.3.0/ref/netstandard1.3/System.IO.Compression.dll
         -r:/home/alex/.nuget/packages/system.io.compression.zipfile/4.3.0/ref/netstandard1.3/System.IO.Compression.ZipFile.dll
         -r:/home/alex/.nuget/packages/system.io/4.3.0/ref/netstandard1.5/System.IO.dll
         -r:/home/alex/.nuget/packages/system.io.filesystem/4.3.0/ref/netstandard1.3/System.IO.FileSystem.dll
         -r:/home/alex/.nuget/packages/system.io.filesystem.primitives/4.3.0/ref/netstandard1.3/System.IO.FileSystem.Primitives.dll
         -r:/home/alex/.nuget/packages/system.io.filesystem.watcher/4.3.0/ref/netstandard1.3/System.IO.FileSystem.Watcher.dll
         -r:/home/alex/.nuget/packages/system.io.memorymappedfiles/4.3.0/ref/netstandard1.3/System.IO.MemoryMappedFiles.dll
         -r:/home/alex/.nuget/packages/system.io.unmanagedmemorystream/4.3.0/ref/netstandard1.3/System.IO.UnmanagedMemoryStream.dll
         -r:/home/alex/.nuget/packages/system.linq/4.3.0/ref/netstandard1.6/System.Linq.dll
         -r:/home/alex/.nuget/packages/system.linq.expressions/4.3.0/ref/netstandard1.6/System.Linq.Expressions.dll
         -r:/home/alex/.nuget/packages/system.linq.parallel/4.3.0/ref/netstandard1.1/System.Linq.Parallel.dll
         -r:/home/alex/.nuget/packages/system.linq.queryable/4.3.0/ref/netstandard1.0/System.Linq.Queryable.dll
         -r:/home/alex/.nuget/packages/system.net.http/4.3.0/ref/netstandard1.3/System.Net.Http.dll
         -r:/home/alex/.nuget/packages/system.net.nameresolution/4.3.0/ref/netstandard1.3/System.Net.NameResolution.dll
         -r:/home/alex/.nuget/packages/system.net.primitives/4.3.0/ref/netstandard1.3/System.Net.Primitives.dll
         -r:/home/alex/.nuget/packages/system.net.requests/4.3.0/ref/netstandard1.3/System.Net.Requests.dll
         -r:/home/alex/.nuget/packages/system.net.security/4.3.0/ref/netstandard1.3/System.Net.Security.dll
         -r:/home/alex/.nuget/packages/system.net.sockets/4.3.0/ref/netstandard1.3/System.Net.Sockets.dll
         -r:/home/alex/.nuget/packages/system.net.webheadercollection/4.3.0/ref/netstandard1.3/System.Net.WebHeaderCollection.dll
         -r:/home/alex/.nuget/packages/system.numerics.vectors/4.3.0/ref/netstandard1.0/System.Numerics.Vectors.dll
         -r:/home/alex/.nuget/packages/system.objectmodel/4.3.0/ref/netstandard1.3/System.ObjectModel.dll
         -r:/home/alex/.nuget/packages/system.reflection.dispatchproxy/4.3.0/ref/netstandard1.3/System.Reflection.DispatchProxy.dll
         -r:/home/alex/.nuget/packages/system.reflection/4.3.0/ref/netstandard1.5/System.Reflection.dll
         -r:/home/alex/.nuget/packages/system.reflection.extensions/4.3.0/ref/netstandard1.0/System.Reflection.Extensions.dll
         -r:/home/alex/.nuget/packages/system.reflection.metadata/1.4.1/lib/netstandard1.1/System.Reflection.Metadata.dll
         -r:/home/alex/.nuget/packages/system.reflection.primitives/4.3.0/ref/netstandard1.0/System.Reflection.Primitives.dll
         -r:/home/alex/.nuget/packages/system.reflection.typeextensions/4.3.0/ref/netstandard1.5/System.Reflection.TypeExtensions.dll
         -r:/home/alex/.nuget/packages/system.resources.reader/4.3.0/lib/netstandard1.0/System.Resources.Reader.dll
         -r:/home/alex/.nuget/packages/system.resources.resourcemanager/4.3.0/ref/netstandard1.0/System.Resources.ResourceManager.dll
         -r:/home/alex/.nuget/packages/system.runtime/4.3.0/ref/netstandard1.5/System.Runtime.dll
         -r:/home/alex/.nuget/packages/system.runtime.extensions/4.3.0/ref/netstandard1.5/System.Runtime.Extensions.dll
         -r:/home/alex/.nuget/packages/system.runtime.handles/4.3.0/ref/netstandard1.3/System.Runtime.Handles.dll
         -r:/home/alex/.nuget/packages/system.runtime.interopservices/4.3.0/ref/netcoreapp1.1/System.Runtime.InteropServices.dll
         -r:/home/alex/.nuget/packages/system.runtime.interopservices.runtimeinformation/4.3.0/ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll
         -r:/home/alex/.nuget/packages/system.runtime.numerics/4.3.0/ref/netstandard1.1/System.Runtime.Numerics.dll
         -r:/home/alex/.nuget/packages/system.security.cryptography.algorithms/4.3.0/ref/netstandard1.6/System.Security.Cryptography.Algorithms.dll
         -r:/home/alex/.nuget/packages/system.security.cryptography.encoding/4.3.0/ref/netstandard1.3/System.Security.Cryptography.Encoding.dll
         -r:/home/alex/.nuget/packages/system.security.cryptography.primitives/4.3.0/ref/netstandard1.3/System.Security.Cryptography.Primitives.dll
         -r:/home/alex/.nuget/packages/system.security.cryptography.x509certificates/4.3.0/ref/netstandard1.4/System.Security.Cryptography.X509Certificates.dll
         -r:/home/alex/.nuget/packages/system.security.principal/4.3.0/ref/netstandard1.0/System.Security.Principal.dll
         -r:/home/alex/.nuget/packages/system.text.encoding/4.3.0/ref/netstandard1.3/System.Text.Encoding.dll
         -r:/home/alex/.nuget/packages/system.text.encoding.extensions/4.3.0/ref/netstandard1.3/System.Text.Encoding.Extensions.dll
         -r:/home/alex/.nuget/packages/system.text.regularexpressions/4.3.0/ref/netcoreapp1.1/System.Text.RegularExpressions.dll
         -r:/home/alex/.nuget/packages/system.threading/4.3.0/ref/netstandard1.3/System.Threading.dll
         -r:/home/alex/.nuget/packages/system.threading.tasks.dataflow/4.7.0/lib/netstandard1.1/System.Threading.Tasks.Dataflow.dll
         -r:/home/alex/.nuget/packages/system.threading.tasks/4.3.0/ref/netstandard1.3/System.Threading.Tasks.dll
         -r:/home/alex/.nuget/packages/system.threading.tasks.extensions/4.3.0/lib/netstandard1.0/System.Threading.Tasks.Extensions.dll
         -r:/home/alex/.nuget/packages/system.threading.tasks.parallel/4.3.0/ref/netstandard1.1/System.Threading.Tasks.Parallel.dll
         -r:/home/alex/.nuget/packages/system.threading.thread/4.3.0/ref/netstandard1.3/System.Threading.Thread.dll
         -r:/home/alex/.nuget/packages/system.threading.threadpool/4.3.0/ref/netstandard1.3/System.Threading.ThreadPool.dll
         -r:/home/alex/.nuget/packages/system.threading.timer/4.3.0/ref/netstandard1.2/System.Threading.Timer.dll
         -r:/home/alex/.nuget/packages/system.xml.readerwriter/4.3.0/ref/netstandard1.3/System.Xml.ReaderWriter.dll
         -r:/home/alex/.nuget/packages/system.xml.xdocument/4.3.0/ref/netstandard1.3/System.Xml.XDocument.dll
         --target:exe
         --warn:4
         --warnaserror:76
         --fullpaths
         --flaterrors
         --highentropyva-
         --targetprofile:netcore
         --simpleresolution
         --nocopyfsharpcore
         /home/alex/dotnet/Program.fs
         
         The specified framework 'Microsoft.NETCore.App', version '1.0.1' was not found.
           - Check application dependencies and target a framework version installed at:
               /opt/dotnet/shared/Microsoft.NETCore.App
           - The following versions are installed:
               1.1.1
           - Alternatively, install the framework version '1.0.1'.
     1>/home/alex/.nuget/packages/fsharp.net.sdk/1.0.2/build/FSharp.NET.Core.Sdk.targets(170,9): error MSB6006: "dotnet" exited with code 131. [/home/alex/dotnet/dotnet.fsproj]
       GenerateBuildDependencyFile:
       Skipping target "GenerateBuildDependencyFile" because all output files are up-to-date with respect to the input files.
     1>Done Building Project "/home/alex/dotnet/dotnet.fsproj" (Build target(s)) -- FAILED.

Build FAILED.

       "/home/alex/dotnet/dotnet.fsproj" (Build target) (1) ->
       (CoreCompile target) -> 
         /home/alex/.nuget/packages/fsharp.net.sdk/1.0.2/build/FSharp.NET.Core.Sdk.targets(170,9): error MSB6006: "dotnet" exited with code 131. [/home/alex/dotnet/dotnet.fsproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.02
```

**Comment by stanuku** [comment]
@enricosada  I've the same issue with Ubuntu **16.04**. I installed .NET Core **1.0.4 SDK**. Then did ```dotnet new mvc -lang F#```. Then ```dotnet build``` fails. 

This is output from ```dotnet --info```

```.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.4```

**Comment by basabuber** [comment]
The same problem for me, but on Ubuntu 17.04:

$ dotnet --info
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  17.04
 OS Platform: Linux
 RID:         ubuntu.16.10-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.4
miki@ubuntu-zesty-ii:~/code/F#/misc-i$ dotnet clean
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

miki@ubuntu-zesty-ii:~/code/F#/misc-i$ clear; dotnet build -v n

Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 5/28/17 6:19:11 PM.
     1>Project "/home/miki/code/F#/misc-i/misc-i.fsproj" on node 1 (Build target(s)).
     1>CoreCompile:
         /usr/share/dotnet/sdk/1.0.4/Sdks/../../../dotnet  "/home/miki/.nuget/packages/fsharp.compiler.tools/4.1.17/build/netcoreapp1.0/fsc.dll" -o:obj/Debug/netcoreapp1.1/misc-i.dll
         -g
         --debug:portable
         --noframework
         --define:DEBUG
         --define:NETCOREAPP1_1
         --optimize-
         -r:/home/miki/.nuget/packages/fsharp.core/4.1.17/lib/netstandard1.6/FSharp.Core.dll
         -r:/home/miki/.nuget/packages/microsoft.csharp/4.3.0/ref/netstandard1.0/Microsoft.CSharp.dll
         -r:/home/miki/.nuget/packages/microsoft.visualbasic/10.1.0/ref/netstandard1.1/Microsoft.VisualBasic.dll
         -r:/home/miki/.nuget/packages/microsoft.win32.primitives/4.3.0/ref/netstandard1.3/Microsoft.Win32.Primitives.dll
         -r:/home/miki/.nuget/packages/system.appcontext/4.3.0/ref/netstandard1.6/System.AppContext.dll
         -r:/home/miki/.nuget/packages/system.buffers/4.3.0/lib/netstandard1.1/System.Buffers.dll
         -r:/home/miki/.nuget/packages/system.collections.concurrent/4.3.0/ref/netstandard1.3/System.Collections.Concurrent.dll
         -r:/home/miki/.nuget/packages/system.collections/4.3.0/ref/netstandard1.3/System.Collections.dll
         -r:/home/miki/.nuget/packages/system.collections.immutable/1.3.0/lib/netstandard1.0/System.Collections.Immutable.dll
         -r:/home/miki/.nuget/packages/system.componentmodel.annotations/4.3.0/ref/netstandard1.4/System.ComponentModel.Annotations.dll
         -r:/home/miki/.nuget/packages/system.componentmodel/4.3.0/ref/netstandard1.0/System.ComponentModel.dll
         -r:/home/miki/.nuget/packages/system.console/4.3.0/ref/netstandard1.3/System.Console.dll
         -r:/home/miki/.nuget/packages/system.diagnostics.debug/4.3.0/ref/netstandard1.3/System.Diagnostics.Debug.dll
         -r:/home/miki/.nuget/packages/system.diagnostics.diagnosticsource/4.3.1/lib/netstandard1.3/System.Diagnostics.DiagnosticSource.dll
         -r:/home/miki/.nuget/packages/system.diagnostics.process/4.3.0/ref/netstandard1.4/System.Diagnostics.Process.dll
         -r:/home/miki/.nuget/packages/system.diagnostics.tools/4.3.0/ref/netstandard1.0/System.Diagnostics.Tools.dll
         -r:/home/miki/.nuget/packages/system.diagnostics.tracing/4.3.0/ref/netstandard1.5/System.Diagnostics.Tracing.dll
         -r:/home/miki/.nuget/packages/system.dynamic.runtime/4.3.0/ref/netstandard1.3/System.Dynamic.Runtime.dll
         -r:/home/miki/.nuget/packages/system.globalization.calendars/4.3.0/ref/netstandard1.3/System.Globalization.Calendars.dll
         -r:/home/miki/.nuget/packages/system.globalization/4.3.0/ref/netstandard1.3/System.Globalization.dll
         -r:/home/miki/.nuget/packages/system.globalization.extensions/4.3.0/ref/netstandard1.3/System.Globalization.Extensions.dll
         -r:/home/miki/.nuget/packages/system.io.compression/4.3.0/ref/netstandard1.3/System.IO.Compression.dll
         -r:/home/miki/.nuget/packages/system.io.compression.zipfile/4.3.0/ref/netstandard1.3/System.IO.Compression.ZipFile.dll
         -r:/home/miki/.nuget/packages/system.io/4.3.0/ref/netstandard1.5/System.IO.dll
         -r:/home/miki/.nuget/packages/system.io.filesystem/4.3.0/ref/netstandard1.3/System.IO.FileSystem.dll
         -r:/home/miki/.nuget/packages/system.io.filesystem.primitives/4.3.0/ref/netstandard1.3/System.IO.FileSystem.Primitives.dll
         -r:/home/miki/.nuget/packages/system.io.filesystem.watcher/4.3.0/ref/netstandard1.3/System.IO.FileSystem.Watcher.dll
         -r:/home/miki/.nuget/packages/system.io.memorymappedfiles/4.3.0/ref/netstandard1.3/System.IO.MemoryMappedFiles.dll
         -r:/home/miki/.nuget/packages/system.io.unmanagedmemorystream/4.3.0/ref/netstandard1.3/System.IO.UnmanagedMemoryStream.dll
         -r:/home/miki/.nuget/packages/system.linq/4.3.0/ref/netstandard1.6/System.Linq.dll
         -r:/home/miki/.nuget/packages/system.linq.expressions/4.3.0/ref/netstandard1.6/System.Linq.Expressions.dll
         -r:/home/miki/.nuget/packages/system.linq.parallel/4.3.0/ref/netstandard1.1/System.Linq.Parallel.dll
         -r:/home/miki/.nuget/packages/system.linq.queryable/4.3.0/ref/netstandard1.0/System.Linq.Queryable.dll
         -r:/home/miki/.nuget/packages/system.net.http/4.3.2/ref/netstandard1.3/System.Net.Http.dll
         -r:/home/miki/.nuget/packages/system.net.nameresolution/4.3.0/ref/netstandard1.3/System.Net.NameResolution.dll
         -r:/home/miki/.nuget/packages/system.net.primitives/4.3.0/ref/netstandard1.3/System.Net.Primitives.dll
         -r:/home/miki/.nuget/packages/system.net.requests/4.3.0/ref/netstandard1.3/System.Net.Requests.dll
         -r:/home/miki/.nuget/packages/system.net.security/4.3.1/ref/netstandard1.3/System.Net.Security.dll
         -r:/home/miki/.nuget/packages/system.net.sockets/4.3.0/ref/netstandard1.3/System.Net.Sockets.dll
         -r:/home/miki/.nuget/packages/system.net.webheadercollection/4.3.0/ref/netstandard1.3/System.Net.WebHeaderCollection.dll
         -r:/home/miki/.nuget/packages/system.numerics.vectors/4.3.0/ref/netstandard1.0/System.Numerics.Vectors.dll
         -r:/home/miki/.nuget/packages/system.objectmodel/4.3.0/ref/netstandard1.3/System.ObjectModel.dll
         -r:/home/miki/.nuget/packages/system.reflection.dispatchproxy/4.3.0/ref/netstandard1.3/System.Reflection.DispatchProxy.dll
         -r:/home/miki/.nuget/packages/system.reflection/4.3.0/ref/netstandard1.5/System.Reflection.dll
         -r:/home/miki/.nuget/packages/system.reflection.extensions/4.3.0/ref/netstandard1.0/System.Reflection.Extensions.dll
         -r:/home/miki/.nuget/packages/system.reflection.metadata/1.4.1/lib/netstandard1.1/System.Reflection.Metadata.dll
         -r:/home/miki/.nuget/packages/system.reflection.primitives/4.3.0/ref/netstandard1.0/System.Reflection.Primitives.dll
         -r:/home/miki/.nuget/packages/system.reflection.typeextensions/4.3.0/ref/netstandard1.5/System.Reflection.TypeExtensions.dll
         -r:/home/miki/.nuget/packages/system.resources.reader/4.3.0/lib/netstandard1.0/System.Resources.Reader.dll
         -r:/home/miki/.nuget/packages/system.resources.resourcemanager/4.3.0/ref/netstandard1.0/System.Resources.ResourceManager.dll
         -r:/home/miki/.nuget/packages/system.runtime/4.3.0/ref/netstandard1.5/System.Runtime.dll
         -r:/home/miki/.nuget/packages/system.runtime.extensions/4.3.0/ref/netstandard1.5/System.Runtime.Extensions.dll
         -r:/home/miki/.nuget/packages/system.runtime.handles/4.3.0/ref/netstandard1.3/System.Runtime.Handles.dll
         -r:/home/miki/.nuget/packages/system.runtime.interopservices/4.3.0/ref/netcoreapp1.1/System.Runtime.InteropServices.dll
         -r:/home/miki/.nuget/packages/system.runtime.interopservices.runtimeinformation/4.3.0/ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll
         -r:/home/miki/.nuget/packages/system.runtime.numerics/4.3.0/ref/netstandard1.1/System.Runtime.Numerics.dll
         -r:/home/miki/.nuget/packages/system.security.cryptography.algorithms/4.3.0/ref/netstandard1.6/System.Security.Cryptography.Algorithms.dll
         -r:/home/miki/.nuget/packages/system.security.cryptography.encoding/4.3.0/ref/netstandard1.3/System.Security.Cryptography.Encoding.dll
         -r:/home/miki/.nuget/packages/system.security.cryptography.primitives/4.3.0/ref/netstandard1.3/System.Security.Cryptography.Primitives.dll
         -r:/home/miki/.nuget/packages/system.security.cryptography.x509certificates/4.3.0/ref/netstandard1.4/System.Security.Cryptography.X509Certificates.dll
         -r:/home/miki/.nuget/packages/system.security.principal/4.3.0/ref/netstandard1.0/System.Security.Principal.dll
         -r:/home/miki/.nuget/packages/system.text.encoding/4.3.0/ref/netstandard1.3/System.Text.Encoding.dll
         -r:/home/miki/.nuget/packages/system.text.encoding.extensions/4.3.0/ref/netstandard1.3/System.Text.Encoding.Extensions.dll
         -r:/home/miki/.nuget/packages/system.text.regularexpressions/4.3.0/ref/netcoreapp1.1/System.Text.RegularExpressions.dll
         -r:/home/miki/.nuget/packages/system.threading/4.3.0/ref/netstandard1.3/System.Threading.dll
         -r:/home/miki/.nuget/packages/system.threading.tasks.dataflow/4.7.0/lib/netstandard1.1/System.Threading.Tasks.Dataflow.dll
         -r:/home/miki/.nuget/packages/system.threading.tasks/4.3.0/ref/netstandard1.3/System.Threading.Tasks.dll
         -r:/home/miki/.nuget/packages/system.threading.tasks.extensions/4.3.0/lib/netstandard1.0/System.Threading.Tasks.Extensions.dll
         -r:/home/miki/.nuget/packages/system.threading.tasks.parallel/4.3.0/ref/netstandard1.1/System.Threading.Tasks.Parallel.dll
         -r:/home/miki/.nuget/packages/system.threading.thread/4.3.0/ref/netstandard1.3/System.Threading.Thread.dll
         -r:/home/miki/.nuget/packages/system.threading.threadpool/4.3.0/ref/netstandard1.3/System.Threading.ThreadPool.dll
         -r:/home/miki/.nuget/packages/system.threading.timer/4.3.0/ref/netstandard1.2/System.Threading.Timer.dll
         -r:/home/miki/.nuget/packages/system.xml.readerwriter/4.3.0/ref/netstandard1.3/System.Xml.ReaderWriter.dll
         -r:/home/miki/.nuget/packages/system.xml.xdocument/4.3.0/ref/netstandard1.3/System.Xml.XDocument.dll
         --target:exe
         --warn:4
         --warnaserror:76
         --fullpaths
         --flaterrors
         --highentropyva-
         --targetprofile:netcore
         --simpleresolution
         --nocopyfsharpcore
         /home/miki/code/F#/misc-i/Program.fs
         
         The specified framework 'Microsoft.NETCore.App', version '1.0.1' was not found.
           - Check application dependencies and target a framework version installed at:
               /usr/share/dotnet/shared/Microsoft.NETCore.App
           - The following versions are installed:
               1.1.2
           - Alternatively, install the framework version '1.0.1'.
     1>/home/miki/.nuget/packages/fsharp.net.sdk/1.0.5/build/FSharp.NET.Core.Sdk.targets(170,9): error MSB6006: "dotnet" exited with code 131. [/home/miki/code/F#/misc-i/misc-i.fsproj]
     1>Done Building Project "/home/miki/code/F#/misc-i/misc-i.fsproj" (Build target(s)) -- FAILED.

Build FAILED.

       "/home/miki/code/F#/misc-i/misc-i.fsproj" (Build target) (1) ->
       (CoreCompile target) -> 
         /home/miki/.nuget/packages/fsharp.net.sdk/1.0.5/build/FSharp.NET.Core.Sdk.targets(170,9): error MSB6006: "dotnet" exited with code 131. [/home/miki/code/F#/misc-i/misc-i.fsproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.06

**Comment by enricosada** [comment]
An update. Not good news, sry.

So, in the last three months LOTS of stuff/dynamics changed for f# and sdk integration (and personally i used lot of time in discussions and reading code instead of fix bugs like this one).

Until now, for sdk 1.0 msbuild based, F# integration was based on `FSharp.NET.Sdk` package (before with project.json based was done with `dotnet-compile-fsc`)

`FSharp.NET.Sdk` was deprecated by following RFCs, and F# integration will be included in `Microsoft.NET.Sdk` in sdk 2.0.

ref [F# RFC FS-1032](https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1032-fsharp-in-dotnet-sdk.md) and [F# RFC FS-1034](https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1034-fsharp-core-package.md).

**`FSharp.NET.Sdk` will continue to work and be maintained, where the LTS version (1.0) of .net core runtime is supported (current situation)**.

Atm it doesnt works when the only runtime avaiable is the 1.1, and that's this issue for some OS.
The real problem of this issue is F# is not supported on OS, where .net core instead is.

What was choosen for F# moving forward is ok, but is developed on different codebase, so working on deprecated code mean not work on the new one, because mechanisms are also a bit different (see [summary of changes between 1.0 and 2.0](https://github.com/dotnet/netcorecli-fsc/wiki/How-to-migrate-1.0-projects-to-2.0#summary-of-changes-from-10-to-20) )

PR are welcome obv
But realistically, noone step up to do it in the meanwhile, and is not going to do it soon. is ok.

Personally, i am not going to fix it. I was sure to be able to find time to do it, but after discussions and deprecation i cannot, because i prefer to work on sdk 2.0 codebase.
Why? the .net core 2.0 runtime is really near rtm, and this issue will not exists there for F# using sdk 2.0. 
And because things changed, is ihmo better to fully work on sdk 2.0, to test and fix bugs and add missing implementations.

**So after triage, closing this as `wont-fix` (PR to fix this are welcome!), F# will be supported on the OS affected by this issue in the next sdk 2.0 afaik**. please test that.

More info in [2.0.0-preview2](https://github.com/dotnet/netcorecli-fsc/wiki/.NET-Core-SDK-2.0.0-preview2)
