### ISSUE TITLE
Some links are dead in the FSharp .Net Core FAQ.

### ISSUE THREAD

**Issue by OnurGumus** [dotnet/netcorecli-fsc#95]
Some 'docs' link in [https://github.com/dotnet/netcorecli-fsc/wiki/FAQ](https://github.com/dotnet/netcorecli-fsc/wiki/FAQ) are dead.

**Comment by enricosada** [comment]
thx @OnurGumus for notification, i updated it, removing stale content too.

BTW wiki is free to edit for everyone, so if a link is broken, or something is not accurate, feel free to edit it.

**Comment by OnurGumus** [comment]
I would edit myself but couldn't make a correlation with some links. Also I still see dead links:
How can i install it?
See the docs --> this is dead for example.

**Comment by OnurGumus** [comment]
This is also dead:
This is a FAQ, where are the real docs?
The docs --> dead are really nice to read, and explain all scenarios.
